apiVersion: v1
kind: Pod
metadata:
  labels:
    app: stackanetes
  name: stackanetes-deployer
spec:
  restartPolicy: OnFailure
  containers:
  - name: stackanetes-base
    #insert a valid image name
    image: quay.io/stackanetes/stackanetes-deployer:2.0.0
    env:
    - name: HOST_INTERFACE
      value: "eno2" #name of physical interface for compute-node
