---
####################
# Docker
####################
searchlight_api_image: "{{ docker_registry ~ '/' if docker_registry else '' }}{{ docker_namespace }}/{{ kolla_base_distro }}-{{ kolla_install_type }}-searchlight-api"
searchlight_api_tag: "{{ openstack_release }}"
searchlight_api_image_full: "{{ searchlight_api_image }}:{{ searchlight_api_tag }}"

####################
# Openstack
####################
searchlight_admin_endpoint: "http://{{ searchlight_api_host }}:{{ searchlight_api_port }}"
searchlight_internal_endpoint: "http://{{ searchlight_api_host }}:{{ searchlight_api_port }}"
searchlight_public_endpoint: "http://{{ searchlight_api_host }}:{{ searchlight_api_port }}"
searchlight_logging_debug: "{{ openstack_logging_debug }}"
searchlight_keystone_user: "searchlight"
openstack_searchlight_auth: "{'auth_url':'{{ openstack_auth_url }}','username':'{{ openstack_username }}','password':'{{ openstack_password }}','project_name':'{{ openstack_project_name }}','domain_name':'default'}"
