---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
spec:
  ports:
  - name: zookeeper1
    port: 2181
    protocol: TCP
    targetPort: 2181
    nodePort: 30000
  - name: zookeeper2
    port: 2888
    protocol: TCP
    targetPort: 2888
  - name: zookeeper3
    port: 3888
    protocol: TCP
    targetPort: 3888
  type: NodePort
  selector:
    app: zookeeper

---

apiVersion: v1
kind: Pod
metadata:
  labels:
    app: zookeeper
    zookeeper_node: zookeeper1
  name: zookeeper1
spec:
  containers:
  - image: jplock/zookeeper
    name: zookeeper
    env:
      - name: MYID
        value: "1"
    command:
    - bash
    - "-c"
    - >-
      mkdir -p /opt/zookeeper/conf
   
      mkdir -p /var/lib/zookeeper/

      echo "$MYID" > /var/lib/zookeeper/myid

      echo "server.1=0.0.0.0:2888:3888" > /opt/zookeeper/conf/zoo.cfg

      echo "server.2=zookeeper2.default.svc.cluster.local:2888:3888" >> /opt/zookeeper/conf/zoo.cfg

      echo "server.3=zookeeper3.default.svc.cluster.local:2888:3888" >> /opt/zookeeper/conf/zoo.cfg

      echo "dataDir=/var/lib/zookeeper" >> /opt/zookeeper/conf/zoo.cfg

      echo "clientPort=2181" >> /opt/zookeeper/conf/zoo.cfg

      echo "initLimit=10" >> /opt/zookeeper/conf/zoo.cfg

      echo "syncLimit=6" >> /opt/zookeeper/conf/zoo.cfg

      /opt/zookeeper/bin/zkServer.sh start-foreground

    ports:
    - containerPort: 2181
      name: zookeeper1
      protocol: TCP
    - containerPort: 2888
      name: zookeeper2
      protocol: TCP
    - containerPort: 3888
      name: zookeeper3
      protocol: TCP
    readinessProbe:
      tcpSocket:
        port: 2181
  restartPolicy: Never
  nodeSelector:
    app: persistent-control
---

apiVersion: v1
kind: Service
metadata:
  labels:
    zookeeper_node: zookeeper1
  name: zookeeper1
spec:
  ports:
  - name: zookeeper1
    port: 2181
    protocol: TCP
    targetPort: 2181
  - name: zookeeper2
    port: 2888
    protocol: TCP
    targetPort: 2888
  - name: zookeeper3
    port: 3888
    protocol: TCP
    targetPort: 3888
  selector:
    zookeeper_node: zookeeper1

---

apiVersion: v1
kind: Pod
metadata:
  labels:
    app: zookeeper
    zookeeper_node: zookeeper2
  name: zookeeper2
spec:
  containers:
  - image: jplock/zookeeper
    name: zookeeper
    env:
      - name: MYID
        value: "2"
    command:
    - bash
    - "-c"
    - >-
      mkdir -p /opt/zookeeper/conf

      mkdir -p /var/lib/zookeeper/

      echo "$MYID" > /var/lib/zookeeper/myid

      echo "server.1=zookeeper1.default.svc.cluster.local:2888:3888" > /opt/zookeeper/conf/zoo.cfg

      echo "server.2=0.0.0.0:2888:3888" >> /opt/zookeeper/conf/zoo.cfg

      echo "server.3=zookeeper3.default.svc.cluster.local:2888:3888" >> /opt/zookeeper/conf/zoo.cfg

      echo "dataDir=/var/lib/zookeeper" >> /opt/zookeeper/conf/zoo.cfg

      echo "clientPort=2181" >> /opt/zookeeper/conf/zoo.cfg

      echo "initLimit=10" >> /opt/zookeeper/conf/zoo.cfg

      echo "syncLimit=6" >> /opt/zookeeper/conf/zoo.cfg

      /opt/zookeeper/bin/zkServer.sh start-foreground

    ports:
    - containerPort: 2181
      name: zookeeper1
      protocol: TCP
    - containerPort: 2888
      name: zookeeper2
      protocol: TCP
    - containerPort: 3888
      name: zookeeper3
      protocol: TCP
    readinessProbe:
      tcpSocket:
        port: 2181
  restartPolicy: Never
  nodeSelector:
    app: persistent-control
---

apiVersion: v1
kind: Service
metadata:
  labels:
    zookeeper_node: zookeeper2
  name: zookeeper2
spec:
  ports:
  - name: zookeeper1
    port: 2181
    protocol: TCP
    targetPort: 2181
  - name: zookeeper2
    port: 2888
    protocol: TCP
    targetPort: 2888
  - name: zookeeper3
    port: 3888
    protocol: TCP
    targetPort: 3888
  selector:
    zookeeper_node: zookeeper2

---

apiVersion: v1
kind: Pod
metadata:
  labels:
    app: zookeeper
    zookeeper_node: zookeeper3
  name: zookeeper3
spec:
  containers:
  - image: jplock/zookeeper
    name: zookeeper
    env:
      - name: MYID
        value: "3"
    command:
    - bash
    - "-c"
    - >-
      mkdir -p /opt/zookeeper/conf

      mkdir -p /var/lib/zookeeper/

      echo "$MYID" > /var/lib/zookeeper/myid

      echo "server.1=zookeeper1.default.svc.cluster.local:2888:3888" > /opt/zookeeper/conf/zoo.cfg

      echo "server.2=zookeeper2.default.svc.cluster.local:2888:3888" >> /opt/zookeeper/conf/zoo.cfg

      echo "server.3=0.0.0.0:2888:3888" >> /opt/zookeeper/conf/zoo.cfg

      echo "dataDir=/var/lib/zookeeper" >> /opt/zookeeper/conf/zoo.cfg

      echo "clientPort=2181" >> /opt/zookeeper/conf/zoo.cfg

      echo "initLimit=10" >> /opt/zookeeper/conf/zoo.cfg

      echo "syncLimit=6" >> /opt/zookeeper/conf/zoo.cfg

      /opt/zookeeper/bin/zkServer.sh start-foreground

    ports:
    - containerPort: 2181
      name: zookeeper1
      protocol: TCP
    - containerPort: 2888
      name: zookeeper2
      protocol: TCP
    - containerPort: 3888
      name: zookeeper3
      protocol: TCP
    readinessProbe:
      tcpSocket:
        port: 2181
  restartPolicy: Never
  nodeSelector:
    app: persistent-control
---

apiVersion: v1
kind: Service
metadata:
  labels:
    zookeeper_node: zookeeper3
  name: zookeeper3
spec:
  ports:
  - name: zookeeper1
    port: 2181
    protocol: TCP
    targetPort: 2181
  - name: zookeeper2
    port: 2888
    protocol: TCP
    targetPort: 2888
  - name: zookeeper3
    port: 3888
    protocol: TCP
    targetPort: 3888
  selector:
    zookeeper_node: zookeeper3
