---
apiVersion: v1
kind: Service
metadata:
  name: keystone-api
spec:
  ports:
  - name: keystone-api1
    port: 5000
    protocol: TCP
    targetPort: 5000
  - name: keystone-api2
    port: 35357
    protocol: TCP
    targetPort: 35357
  selector:
    app: keystone-api

---

apiVersion: v1
kind: ReplicationController
metadata:
  name: keystone-api
spec:
  replicas: 1
  selector:
    app: keystone-api
  template:
    metadata:
      labels:
        app: keystone-api
      name: keystone-api
    spec:
      nodeSelector:
        app: non-persistent-control
      containers:
        - name: keystone-api
          image: quay.io/stackanetes/centos-binary-keystone:2.0.0
          env:
            - name: KOLLA_SKIP_EXTEND_START
              value: ""
            - name: KOLLA_CONFIG_STRATEGY
              value: COPY_ONCE
            - name: KOLLA_CONFIG
              value: '{"command": "kolla_mesos_start","config_files":[{"source": "zk://zookeeper:2181/kolla/common/kolla_mesos_start.py","dest": "/usr/local/bin/kolla_mesos_start","owner": "root","perm": "0755"}]}'
            - name: KOLLA_LOGLEVEL
              value: info
            - name: KOLLA_ZK_HOSTS
              value: zookeeper:2181
            - name: KOLLA_PRIVATE_INTERFACE
              value: eth0
            - name: KOLLA_PUBLIC_INTERFACE
              value: eth0
            - name: ZK_APP_ID
              value: /root/openstack/keystone/keystone-api
          ports:
          - containerPort: 5000
            name: keystone-api1
            protocol: TCP
          - containerPort: 35357
            name: keystone-api2
            protocol: TCP
          resources:
            limits:
              memory: 4000Mi
