---
apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  ports:
  - name: mariadb
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mariadb

---

apiVersion: v1
kind: ReplicationController
metadata:
  name: mariadb
spec:
  replicas: 1
  selector:
    app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
      name: mariadb
    spec:
      nodeSelector:
        app: persistent-control
      containers:
        - name: mariadb
          image: quay.io/stackanetes/centos-binary-mariadb:2.0.0
          env:
            - name: KOLLA_SKIP_EXTEND_START
              value: ""
            - name: KOLLA_CONFIG_STRATEGY
              value: COPY_ONCE
            - name: KOLLA_CONFIG
              value: '{"command": "kolla_mesos_start","config_files":[{"source": "zk://zookeeper:2181/kolla/common/kolla_mesos_start.py","dest": "/usr/local/bin/kolla_mesos_start","owner": "root","perm": "0755"}]}'
            - name: KOLLA_LOGLEVEL
              value: info
            - name: KOLLA_ZK_HOSTS
              value: zookeeper:2181
            - name: KOLLA_PRIVATE_INTERFACE
              value: eth0
            - name: KOLLA_PUBLIC_INTERFACE
              value: eth0
            - name: ZK_APP_ID
              value: /root/infra/mariadb/mariadb
          ports:
          - containerPort: 3306
            name: mariadb
            protocol: TCP
          resources:
            limits:
              cpu: 0.1
              memory: 4096Mi
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mariadb
      volumes:
        - name: mariadb
          hostPath:
            path: /var/lib/mysql