---
apiVersion: v1
kind: Service
metadata:
  name: neutron-server
spec:
  ports:
  - name: neutron-server1
    port: 9696
    protocol: TCP
    targetPort: 9696
  selector:
    app: neutron-server

---

apiVersion: v1
kind: ReplicationController
metadata:
  name: neutron-server
spec:
  replicas: 1
  selector:
    app: neutron-server
  template:
    metadata:
      labels:
        app: neutron-server
      name: neutron-server
    spec:
      nodeSelector:
        app: non-persistent-control
      containers:
        - name: neutron-server
          command:
          image: quay.io/stackanetes/centos-binary-neutron-server:2.0.0
          env:
            - name: KOLLA_SKIP_EXTEND_START
              value: ""
            - name: KOLLA_CONFIG_STRATEGY
              value: COPY_ONCE
            - name: KOLLA_CONFIG
              value: '{"command": "kolla_mesos_start","config_files":[{"source": "zk://zookeeper:2181/kolla/common/kolla_mesos_start.py","dest": "/usr/local/bin/kolla_mesos_start","owner": "root","perm": "0755"}]}'
            - name: KOLLA_LOGLEVEL
              value: info
            - name: KOLLA_ZK_HOSTS
              value: zookeeper:2181
            - name: KOLLA_PRIVATE_INTERFACE
              value: eth0
            - name: KOLLA_PUBLIC_INTERFACE
              value: eth0
            - name: ZK_APP_ID
              value: /root/openstack/neutron/neutron-server
          ports:
          - containerPort: 9696
            name: glance-api1
            protocol: TCP
          resources:
            limits:
              memory: 4000Mi
