---
apiVersion: v1
kind: Service
metadata:
  name: nova-api
spec:
  ports:
  - name: nova-api1
    port: 8774
    protocol: TCP
    targetPort: 8774
  - name: nova-api2
    port: 8775
    protocol: TCP
    targetPort: 8775
  selector:
    app: nova-api

---

apiVersion: v1
kind: ReplicationController
metadata:
  name: nova-api
spec:
  replicas: 1
  selector:
    app: nova-api
  template:
    metadata:
      labels:
        app: nova-api
      name: nova-api
    spec:
      nodeSelector:
        app: non-persistent-control
      containers:
        - name: nova-api
          securityContext:
            privileged: true
          image: quay.io/stackanetes/centos-binary-nova-api:2.0.0
          env:
            - name: KOLLA_SKIP_EXTEND_START
              value: ""
            - name: KOLLA_CONFIG_STRATEGY
              value: COPY_ONCE
            - name: KOLLA_CONFIG
              value: '{"command": "kolla_mesos_start","config_files":[{"source": "zk://zookeeper:2181/kolla/common/kolla_mesos_start.py","dest": "/usr/local/bin/kolla_mesos_start","owner": "root","perm": "0755"}]}'
            - name: KOLLA_LOGLEVEL
              value: info
            - name: KOLLA_ZK_HOSTS
              value: zookeeper:2181
            - name: KOLLA_PRIVATE_INTERFACE
              value: eth0
            - name: KOLLA_PUBLIC_INTERFACE
              value: eth0
            - name: ZK_APP_ID
              value: /root/openstack/nova/nova-api
          ports:
          - containerPort: 8774
            name: nova-api1
            protocol: TCP
          - containerPort: 8775
            name: nova-api2
            protocol: TCP
          resources:
            limits:
              memory: 4000Mi
