---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  ports:
  - name: rabbitmq
    port: 5672
    protocol: TCP
    targetPort: 5672
  selector:
    app: rabbitmq

---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq
spec:
  nodeSelector:
    app: persistent-control
  containers:
    - name: rabbitmq
      image: quay.io/stackanetes/centos-binary-rabbitmq:2.0.0
      env:
        - name: KOLLA_SKIP_EXTEND_START
          value: ""
        - name: KOLLA_CONFIG_STRATEGY
          value: COPY_ONCE
        - name: KOLLA_CONFIG
          value: '{"command": "kolla_mesos_start","config_files":[{"source": "zk://zookeeper:2181/kolla/common/kolla_mesos_start.py","dest": "/usr/local/bin/kolla_mesos_start","owner": "root","perm": "0755"}]}'
        - name: KOLLA_LOGLEVEL
          value: info
        - name: KOLLA_ZK_HOSTS
          value: zookeeper:2181
        - name: KOLLA_PRIVATE_INTERFACE
          value: eth0
        - name: KOLLA_PUBLIC_INTERFACE
          value: eth0
        - name: ZK_APP_ID
          value: /root/infra/rabbitmq/rabbitmq
      ports:
      - containerPort: 5672
        name: rabbitmq
        protocol: TCP
      resources:
        limits:
          memory: 4096Mi
      volumeMounts:
        - mountPath: /var/log/rabbitmq
          name: rabbitmq-log
  volumes:
    - name: rabbitmq-log
      emptyDir: {}