---
apiVersion: v1
kind: Service
metadata:
  name: horizon
spec:
  ports:
  - name: horizon1
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 31000
  - name: horizon2
    port: 443
    protocol: TCP
    targetPort: 443
  type: NodePort
  selector:
    app: horizon

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: horizonv2
spec:
  replicas: 1
  selector:
    ver: v2
  template:
    metadata:
      labels:
        ver: v2
        app: horizon
      name: horizonv2
    spec:
      nodeSelector:
        app: non-persistent-control
      containers:
        - name: horizon
          securityContext:
            privileged: true
          image: quay.io/stackanetes/centos-binary-horizon:2.0.0
          env:
            - name: KOLLA_SKIP_EXTEND_START
              value: ""
            - name: KOLLA_CONFIG_STRATEGY
              value: COPY_ONCE
            - name: KOLLA_CONFIG
              value: '{"command": "kolla_mesos_start","config_files":[{"source": "zk://zookeeper:2181/kolla/common/kolla_mesos_start.py","dest": "/usr/local/bin/kolla_mesos_start","owner": "root","perm": "0755"}]}'
            - name: KOLLA_LOGLEVEL
              value: info
            - name: KOLLA_ZK_HOSTS
              value: zookeeper:2181
            - name: KOLLA_PRIVATE_INTERFACE
              value: eth0
            - name: KOLLA_PUBLIC_INTERFACE
              value: eth0
            - name: ZK_APP_ID
              value: /root/openstack/horizon/horizon
          ports:
          - containerPort: 8774
            name: horizon1
            protocol: TCP
          - containerPort: 443
            name: horizon2
            protocol: TCP
          resources:
            limits:
              memory: 4096Mi

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: horizonv3
spec:
  replicas: 0
  selector:
    ver: v3
  template:
    metadata:
      labels:
        app: horizon
        ver: v3
      name: horizonv3
    spec:
      nodeSelector:
        app: non-persistent-control
      containers:
        - name: horizon
          securityContext:
            privileged: true
          image: quay.io/stackanetes/centos-binary-horizon:3.0.0
          env:
            - name: KOLLA_SKIP_EXTEND_START
              value: ""
            - name: KOLLA_CONFIG_STRATEGY
              value: COPY_ONCE
            - name: KOLLA_CONFIG
              value: '{"command": "kolla_mesos_start","config_files":[{"source": "zk://zookeeper:2181/kolla/common/kolla_mesos_start.py","dest": "/usr/local/bin/kolla_mesos_start","owner": "root","perm": "0755"}]}'
            - name: KOLLA_LOGLEVEL
              value: info
            - name: KOLLA_ZK_HOSTS
              value: zookeeper:2181
            - name: KOLLA_PRIVATE_INTERFACE
              value: eth0
            - name: KOLLA_PUBLIC_INTERFACE
              value: eth0
            - name: ZK_APP_ID
              value: /root/openstack/horizon/horizon
          ports:
          - containerPort: 8774
            name: horizon1
            protocol: TCP
          - containerPort: 443
            name: horizon2
            protocol: TCP
          resources:
            limits:
              memory: 4096Mi
