---
apiVersion: v1
kind: ReplicationController
metadata:
  name: nova-conductor
spec:
  replicas: 1
  selector:
    app: nova-conductor
  template:
    metadata:
      labels:
        app: nova-conductor
      name: nova-conductor
    spec:
      nodeSelector:
        app: non-persistent-control
      containers:
        - name: nova-conductor
          securityContext:
            privileged: true
          image: quay.io/stackanetes/centos-binary-nova-conductor:2.0.0
          env:
            - name: KOLLA_SKIP_EXTEND_START
              value: ""
            - name: KOLLA_CONFIG_STRATEGY
              value: COPY_ONCE
            - name: KOLLA_CONFIG
              value: '{"command": "kolla_mesos_start","config_files":[{"source": "zk://zookeeper:2181/kolla/common/kolla_mesos_start.py","dest": "/usr/local/bin/kolla_mesos_start","owner": "root","perm": "0755"}]}'
            - name: KOLLA_LOGLEVEL
              value: info
            - name: KOLLA_ZK_HOSTS
              value: zookeeper:2181
            - name: KOLLA_PRIVATE_INTERFACE
              value: eth0
            - name: KOLLA_PUBLIC_INTERFACE
              value: eth0
            - name: ZK_APP_ID
              value: /root/openstack/nova/nova-conductor
          resources:
            limits:
              memory: 4000Mi
