---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nova_ansible_tasks
  name: nova-init
spec:
  nodeSelector:
    app: non-persistent-control
  restartPolicy: OnFailure
  containers:
    - name: nova-init
      command:
        - kolla_start
      image: quay.io/stackanetes/centos-binary-kolla-toolbox:2.0.0
      env:
        - name: KOLLA_SKIP_EXTEND_START
          value: ""
        - name: KOLLA_CONFIG_STRATEGY
          value: COPY_ONCE
        - name: KOLLA_CONFIG
          value: '{"command": "kolla_mesos_start","config_files":[{"source": "zk://zookeeper:2181/kolla/common/kolla_mesos_start.py","dest": "/usr/local/bin/kolla_mesos_start","owner": "root","perm": "0755"}]}'
        - name: KOLLA_LOGLEVEL
          value: info
        - name: KOLLA_ZK_HOSTS
          value: zookeeper:2181
        - name: KOLLA_PRIVATE_INTERFACE
          value: eth0
        - name: KOLLA_PUBLIC_INTERFACE
          value: eth0
        - name: ZK_APP_ID
          value: /root/openstack/nova/nova_ansible_tasks
        - name: ANSIBLE_LIBRARY
          value: /usr/share/ansible/
        - name: ANSIBLE_NOCOLOR
          value: "1"
      ports:
      - containerPort: 3306
        name: mariadb
        protocol: TCP
      resources:
        limits:
          memory: 4096Mi
