---
apiVersion: v1
kind: Service
metadata:
  name: nova-novncproxy
spec:
  ports:
  - name: nova-novncproxy
    port: 6080
    protocol: TCP
    targetPort: 6080
    nodePort: 32000
  type: NodePort
  selector:
    app: nova-novncproxy


---
apiVersion: v1
kind: ReplicationController
metadata:
  name: nova-novncproxy
spec:
  replicas: 1
  selector:
    app: nova-novncproxy
  template:
    metadata:
      labels:
        app: nova-novncproxy
      name: nova-novncproxy
    spec:
      nodeSelector:
        app: non-persistent-control
      containers:
        - name: nova-novncproxy
          securityContext:
            privileged: true
          image: quay.io/stackanetes/centos-binary-nova-novncproxy:2.0.0
          env:
            - name: KOLLA_SKIP_EXTEND_START
              value: ""
            - name: KOLLA_CONFIG_STRATEGY
              value: COPY_ONCE
            - name: KOLLA_CONFIG
              value: '{"command": "kolla_mesos_start","config_files":[{"source": "zk://zookeeper:2181/kolla/common/kolla_mesos_start.py","dest": "/usr/local/bin/kolla_mesos_start","owner": "root","perm": "0755"}]}'
            - name: KOLLA_LOGLEVEL
              value: info
            - name: KOLLA_ZK_HOSTS
              value: zookeeper:2181
            - name: KOLLA_PRIVATE_INTERFACE
              value: eth0
            - name: KOLLA_PUBLIC_INTERFACE
              value: eth0
            - name: ZK_APP_ID
              value: /root/openstack/nova/nova-novncproxy
          ports:
          - containerPort: 6080
            name: nova-novncproxy
            protocol: TCP
          resources:
            limits:
              memory: 4000Mi
