apiVersion: "v1"
kind: "Service"
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: etcd
  labels:
    k8s-app: etcd-stackanetes
    shard: "{{shard}}"
spec:
  selector:
    k8s-app: etcd-stackanetes
    shard: "{{shard}}"
  type: ClusterIP
#  clusterIP: "None"
  ports:
    - name: etcd-client
      targetPort: 2379
      port: 2379
    - name: etcd-legacy
      targetPort: 4001
      port: 4001
    - name: etcd-peer
      targetPort: 2380
      port: 2380
